// Generated by chorm — do not edit by hand.
// Source database: demo
import { ch, col, table, mergeTree } from "../src/index.ts";

export const events = table(
  "events",
  {
    id: ch.uuid(),
    user_id: ch.uint64(),
    name: ch.lowCardinality(ch.string()),
    status: ch.enum8({ active: 1, inactive: 2 }),
    amount: ch.nullable(ch.decimal(18, 4)),
    tags: ch.array(ch.string()),
    properties: ch.map(ch.string(), ch.string()),
    location: ch.namedTuple({ lat: ch.float64(), lon: ch.float64() }),
    created_at: col(ch.dateTime("UTC"), { default: "now()" }),
    day: col(ch.date(), { materialized: "toDate(created_at)" }),
    state: ch.dynamic("AggregateFunction(uniq, UInt64)"),
  },
  {
    engine: mergeTree(),
    orderBy: ["created_at", "id"],
    partitionBy: "toYYYYMM(created_at)",
    indexes: [
      { name: "idx_user_id", expression: "user_id", type: "bloom_filter(0.01)", granularity: 4 },
      { name: "idx_name", expression: "name", type: "tokenbf_v1(256, 2, 0)", granularity: 1 },
    ],
    ttl: "toDateTime(created_at) + toIntervalYear(1)",
  },
);
